### ISSUE TITLE
Setting in HEROKU results in an error.

### ISSUE THREAD

**Issue by asako08** [companionstudio/instagram-token-agent#2]
After pressing 'Deploy app', it stops at 'Configure environment' and displays a screen asking for credit card registration.

The same name was entered in 'APP name' of 'App name' and 'Config Vars'.
In 'STARTING_TOKEN', the access token created by 'User Token Generator' on the FB development page was entered.

What is the cause?

**Comment by jimmyfisher** [comment]
I have this same issue - looks like it won't let you deploy until you verify with CC.

**Comment by jimmyfisher** [comment]
<img width="406" alt="Screen Shot 2020-03-31 at 1 51 12 PM" src="https://user-images.githubusercontent.com/35467099/78058735-bf2cfe00-7356-11ea-95f2-42ccaf11e20c.png">

<img width="711" alt="Screen Shot 2020-03-31 at 1 52 48 PM" src="https://user-images.githubusercontent.com/35467099/78058866-edaad900-7356-11ea-821a-bf123a955e0c.png">

This is what shows up on the side after filling in an 'available' app name, copy/pasting into the App Name field below it, pasting in the token from FB's generator, and hitting 'Deploy'

**Comment by asako08** [comment]
I solved it by registering a credit card in 'HEROKU'.
'HEROKU' seems to require a credit card registration to use the add-on even with the free plan.

**Comment by jimmyfisher** [comment]
Is there a cost/charge associated with using this deployment though? Or is it just there for verification purposes?

**Comment by asako08** [comment]
Even if you register your credit card, it is registered as 'Free Dyno Usage'.
The code page also says:
'This app is designed to run using free plans and add-ons at Heroku'.

I think it can be used for free.

**Comment by jimmyfisher** [comment]
Does it seem like the 'add-ons' cost anything? Or it's a 'free add-on'?

**Comment by asako08** [comment]
Checking from the management screen of 'HEROKU', all 'add-ons' are free.

However, I have just started using 'HEROKU' and do not know the details.

If you're worried, check with the developer or 'HEROKU'.

**Comment by benjamin-hull** [comment]
Hi @asako08 - my apologies, I have somehow not been receiving notifications for this repo!

I just mentioned in [another issue](https://github.com/companionstudio/instagram-token-agent/issues/3#issuecomment-613482435) that all the addons are free and can remain so (you won't ever run over any of the free limits). The first thing that will hit a limit is the Heroku Free Dyno pool, which has a limited amount of compute per month. Even then, your agent will stop working rather than charge you money.

Workarounds and fixes for this limit are [discussed in the wiki](https://github.com/companionstudio/instagram-token-agent/wiki/Deploying-and-running-on-Heroku#considerations)

**Comment by benjamin-hull** [comment]
Addressed in 4bed93ace1c2cb5e69b1a4a622b458fdf1538652 - Thanks for the heads-up, @asako08  !
