### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by gijslaarman** [companionstudio/instagram-token-agent#7]
I set up the profile with Heroku, added the access token at the bottom. The website is up and running and working as I thought it should, wonderful!

I linked the script tag in my html, but whenever I paste in the fetched `InstagramToken` into instafeed.js I get the following error:

```
Uncaught Error: Error from Instagram: The access_token provided is invalid.
    at e.parse (instafeed.min.js:2)
    at popular?client_id=IGQVJXNVQzdk4tZAVYyRGMzLU5lWGRKZA1NBcXpMV3BtRUxZAMXl3Q254ZAjlxLUVod2tNbkVlMFdNdnI3UDZAOdkp2RjlsLUtFYXU1STFIdTdhM25UbHRxM0ZAJRWpGemVrMjRudExPY2FR&callback=instafeedCache4f4169353586d68e.parse:1
```

But the Heroku App itself _is_ able to fetch the first image of the instagram feed. Is it not returning the wrong access token? Because it's the exact same query/code as the one I pasted into the setup page.

**Comment by benjamin-hull** [comment]
Hi @gijslaarman - apologies for the delayed response!

So, I think the missing piece here is that the access token changes regularly - that's the thing that the Token Agent is designed to handle. You can't take an actual token value and paste it into your code, because it will expire and stop working.

Rather than pasting in the fetched value, you include the Token Agent script, and it provides the live, working access token to Instafeed.js - [check the demo here](https://codepen.io/companionstudio/pen/rNVPGOz) for the simplest method to get it working.

In its simplest form, your instagram token agent script will set a global variable in your page called `InstagramToken` - if you open your console and paste that in, you should see the token value. 

Let me know how you go with that!

**Comment by gijslaarman** [comment]
I copied the demo, put in my own Token Agent script and it's now working!
No clue what is different this time, but will have to figure that out on my own.

Thanks for your help!
